# Jekyll configuration for GitHub Pages
title: "Ambience - Practical Records"
description: "Comprehensive practical records for Computer Science courses"
author: "dorukaysor"
email: "your-email@example.com"
baseurl: "/ambience"
url: "https://iancarter-dev.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: null

# GitHub Pages / Jekyll settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from Jekyll processing
exclude:
  - LICENSE
  - S.md
  - dev.txt
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - DEPLOYMENT.md
  - WEB_README.md
  - "*.md"

# Include files in Jekyll processing - ONLY the interface directory
include:
  - interface/

# Disable Jekyll processing for the interface directory
defaults:
  - scope:
      path: "interface"
    values:
      layout: null

# Collections
collections: {}

# SEO settings
google_analytics: # Add your GA tracking ID here if needed

# Social media
twitter:
  username: # Add your Twitter username if needed

github:
  username: iancarter-dev