# GitHub Pages Configuration for Ambience GUI
title: "Ambience - University Course Records"
description: "A comprehensive collection of practical records, notes, and code snippets for university courses"
url: "https://iancarter-dev.github.io"
baseurl: "/ambience/GUI"

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .nojekyll

# Include files
include:
  - .nojekyll

# Markdown settings
markdown: kramdown
highlighter: rouge

# Collections
collections_dir: record

# SEO settings
author: "Ian Carter"
twitter_username: iancarter-dev
github_username: iancarter-dev

# Theme settings (using default GitHub Pages theme)
theme: minima

# Additional metadata
repository: "iancarter-dev/ambience"
google_analytics: # Add your GA tracking ID if needed