# Jekyll configuration for GitHub Pages
title: "Ambience - Practical Records"
description: "Comprehensive practical records for Computer Science courses"
author: "dorukaysor"
email: "your-email@example.com"
baseurl: "/ambience"
url: "https://iancarter-dev.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: null

# GitHub Pages / Jekyll settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from Jekyll processing
exclude:
  - README.md
  - LICENSE
  - S.md
  - dev.txt
  - config.json
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - DEPLOYMENT.md

# Include files in Jekyll processing
include:
  - .htaccess
  - _pages
  - interface/

# Collections
collections:
  experiments:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "interface"
    values:
      layout: "default"

# SEO settings
google_analytics: # Add your GA tracking ID here if needed

# Social media
twitter:
  username: # Add your Twitter username if needed

github:
  username: iancarter-dev

# Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false